development:
  adapter: postgresql
  encoding: unicode
  database: farm_development
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: farm_test
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: farm_production
  host: localhost
